#!/bin/bash
# Copyright © 2013 Martin Ueding <dev@martin-ueding.de>

set -e
set -u

rm -f *crop.pdf

for p in *Penrose.xoj.pdf
do
	pdfseparate "$p" "${p%.xoj.pdf}-%d.pdf"
done

count=0

for p in *Penrose-*.pdf
do
	pdfcrop "$p"
	count=$(( count + 1 ))
done

echo "$count Penrose-Diagramme"
